[parse]
sourcefile=[ "rollerg.cpp" ]
main="rollerg"

[dipsw]
delete=[{names=["Unused","Unknown"]}]
rename=[ {name="Bonus Energy", values=["1/2 stage","1/4 stage","1/4 cycle","None"] } ]

[ROM]
regions = [
    { name="maincpu" },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="k053260",  start="PCM_START",         rename="pcm"  },
    { name="k051316",  start="JTFRAME_BA2_START", rename="psac" },
    { name="k053244",  start="JTFRAME_BA3_START", width=32, rename="obj" },
]
order = [ "maincpu", "audiocpu", "pcm", "psac", "obj" ]
